# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TestWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(305, 258)
        self.label_1 = QtWidgets.QLabel(Form)
        self.label_1.setGeometry(QtCore.QRect(20, 70, 81, 21))
        self.label_1.setObjectName("label_1")

        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 81, 21))
        self.label_2.setObjectName("label_2")

        self.btnClose = QtWidgets.QPushButton(Form)
        self.btnClose.setGeometry(QtCore.QRect(10, 180, 75, 23))
        self.btnClose.setObjectName("btnClose")

        self.btnNext = QtWidgets.QPushButton(Form)
        self.btnNext.setGeometry(QtCore.QRect(120, 180, 75, 23))
        self.btnNext.setObjectName("btnNext")

        self.lcdNumber = QtWidgets.QLCDNumber(Form)
        self.lcdNumber.setGeometry(QtCore.QRect(130, 70, 64, 23))
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber.value("5")

        self.retranslateUi(Form)
        self.btnClose.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Test Widget"))
        self.label_1.setText(_translate("Form", "Record Number:"))
        self.label_2.setText(_translate("Form", "Record Name"))
        self.btnClose.setText(_translate("Form", "Close Window"))
        self.btnNext.setText(_translate("Form", "Next Record"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
